### ISSUE TITLE
New Updates - Alternative Repo.

### ISSUE THREAD

**Issue by monagjr** [jvolker/miq-nz-booking-tools#130]
Hello everyone, 

I'd like to thank everyone contributed and maintained this code repo.
  
Unfortunately, it seems maintainers are not active for a while, and hence new code changes / updates can't be merged with the main code base.

And given the time sensitivity of the needed updates for this tool, I've created a [new fork](https://github.com/monagjr/miq-nz-booking-tools) and pushed to it the latest Aug 18th update, along with building the needed ready-made [Windows and Mac OS binaries / executable for non-coders](https://github.com/monagjr/miq-nz-booking-tools/releases).

So, I'd suggest we continue our work on the [new repo.](https://github.com/monagjr/miq-nz-booking-tools) for the time being.

Wish everyone will have his/her needed MIQ spot secured.

**Comment by jksmurf** [comment]
Thanks for keeping it up to date and active monagjr, much appreciated, especially for updating the binaries for those of us whom trying to run or merge other versions is challenging. Waiting for later dates but will certainly test over next few days.

**Comment by simimoha** [comment]
Hello . i want someone help me to book

**Comment by monagjr** [comment]
> Hello . i want someone help me to book

Hello @simimoha 

have you tried the software yet? 

you can download its latest version here:
https://github.com/monagjr/miq-nz-booking-tools/releases

**Comment by simimoha** [comment]
Hello.. there is a girl who did to me just now successfully through fiverr.
Do u want me to send you the link for her ..
Talk to her kid give her the required information and she will book for you

**Comment by 7lkf7** [comment]
Thank you very much

**Comment by mouarg** [comment]
@monagjr no hits in the last 24 hours, just wondering if something has been changed again? Or is it just me? Thanks

**Comment by monagjr** [comment]
@mouarg are you targeting/monitoring specific dates only? If yes , which dates?

**Comment by cmartin-kavlifoundation** [comment]
I'm looking for specific dates as well, but I keep a general eye out for any dates.  It has been very quiet the past 24 hours.  The folks monitoring the twitter feed have also commented on how quiet it is.  I checked the calendar code to see if they have changed anything (like they did last week), but it all looks the same.  So just ... quiet.

**Comment by mouarg** [comment]
@monagjr I am yes. Last week of sept, all of Oct and Nov. No sundays in Sep or Oct because the flights dont make sense unfortunately.

It looks like things are just quiet when lookiing at the twitter bot, I was just slightly concerned that maybe they had changed the code again but it doesnt look like they have.

**Comment by mouarg** [comment]
MIQ is temporarily pausing the release of rooms on the Managed Isolation Allocation System due to the current COVID-19 outbreak. This includes cancelled vouchers that are normally re-released. No rooms will be available to book for a few days. Updates will be posted here.

[https://twitter.com/MBIEgovtnz/status/1429689112160837637](url)

**Comment by jvolker** [comment]
Thanks a lot for your effort and updates, @monagjr. 

I’m closing this as I've merged and created new releases: https://github.com/jvolker/miq-nz-booking-tools/releases/latest

However, I have to say, I'm a bit confused by your approach to branch off the project only two days after your pull request. Everyone on this project is doing this voluntary in their spare time while also working full-time jobs. 

Also, I’m not too happy to see someone forking the project and putting their own donation button on the top while removing most parts of the original donation section going to a charity. This does not show the kind of respect to the previous developers and anyone who helped with previous releases I would like to see.

The inequality of MIQ is problematic. Even more, I’m finding it problematic that individuals are making money due to these circumstances. The idea of this project was to provide/improve access to MIQ free of charge. That’s why I choose a charity for anyone who wanted to donate money over a personal donation button. I hope everyone working on this project shares the same values, and I prefer if everyone does it without compensation.

I really appreciate your help, though, and I’m happy about any suggestions you have to improve the project or reduce potential downtimes. 

Everyone is welcome to work on this together.

**Comment by monagjr** [comment]
Hi @jvolker 

It's great to know that the latest releases here now include my shared recent updates.

And like I shared in the first post here "And given the time sensitivity of the needed updates for this tool,", I think this tool / software requires and needs daily action taking. As you already know, the MIQ spots are coming up and going away in seconds, and one needed spot may not appear again. Also, as you may already know, most of ones who use this tool do not have the technical know-how to build the releases / binaries (ready-made to use Windows or MacOS application).
Hence I'd say having even 2 days (let alone more) with no-action after a breaking change like the one happened on Aug 18th, is not the best needed timing for this software.

I'd say the step that you took here #134 is good one on the right path. 👍 

And given our goal is the same which is helping maximum possible people with this challenging situation of booking MIQ spot, you and anyone else are more than welcomed to integrate any updates that I'm adding to my [fork](https://github.com/monagjr/miq-nz-booking-tools).

**Comment by monagjr** [comment]
you are right @mouarg . the reason behinds that quietness is that MIQ has already paused the release of rooms.

**Comment by jvolker** [comment]
> And given our goal is the same which is helping maximum possible people with this challenging situation of booking MIQ spot, you and anyone else are more than welcomed to integrate any updates that I'm adding to my fork.

I put this code together to help others. @alexDrinkwater came in as a collaborator and we were able to work together to improve it and invested quite some time, as have others. It makes the most sense to me if many people can work together to improve it instead of individuals branching off the project and creating multiple environments, which will likely confuse people, especially those who don't have experience using Github. The more people that can work together, the more we will be able to assist people as a collective.

> Also, as you may already know, most of ones who use this tool do not have the technical know-how to build the releases / binaries (ready-made to use Windows or MacOS application).

@alexDrinkwater has been working on the user interface part of this project to remove the requirement for people to write code. And creating binaries is not required by users as we've been creating releases for that purpose. Delays only ever happen when someone needs to review the code.
