### ISSUE TITLE
app unsafe message

### ISSUE THREAD

**Issue by nedmi** [jvolker/miq-nz-booking-tools#31]
HI Jvolker I am not able to open the app you sent it say unsafe? I am not that familiar with the app so unsure anything you can do to helpme understand Thanks just trying to get a spot

**Comment by alexDrinkwater** [comment]
@nedmi Because this is a Beta release of the software we have not certified the application which is why you will see the "unsafe message". Often you can bypass these messages. If you are sure you are opening the download from the [github release](https://github.com/jvolker/miq-nz-booking-tools/releases) then it is safe to bypass the message.

**Comment by alexDrinkwater** [comment]
Closing this because it costs lots of $$$ to certify the app
