### ISSUE TITLE
Nothing happens when clicking 'next' after a date is found

### ISSUE THREAD

**Issue by HKG2301** [jvolker/miq-nz-booking-tools#44]
Firstly, many thanks to Jeremias & Alex for all the work you're putting into this. This crazy MIQ system would be impossible to navigate without this script.

I'm looking for a slot in Nov and had two hits over the last three days. I very quickly selected the date (the new highlighted date worked a treat, thanks), checked the reCaptcha and then the bold 'Next'. Each time nothing happened, except the script stopped running, with the message line changing from 'Checked MIQ: xxx' to 'Success' or some such.

I had expected to move further in the booking process. Maybe I was just too slow?

Of note, checking my Chrome Version I found that it needed an update from 91.0.4472.124 to 91.0.4472.164 - not sure if that was a factor?

**Comment by alexDrinkwater** [comment]
Wait for the beep sound, then select the available date and continue booking by clicking "I'm not a robot" and then "Next".

**Comment by HKG2301** [comment]
You didn't really read my question, did you Alex?

**Comment by alexDrinkwater** [comment]
@HKG2301 Sorry, lots of issues have been coming in lately that are duplicates. Could you please give more detail about what happened? Did the page reload and you went back to the calendar with no date? How long did you watch it after clicking next? After you clicked 'next' was it still bold? The experience you described is similar to what happens when you click next and someone else has already taken the spot milliseconds before you. The page essentially refreshes and looks like nothing happened.

**Comment by alexDrinkwater** [comment]
@HKG2301 Please reopen if you believe this is still an issue.
