### ISSUE TITLE
Date picker not working

### ISSUE THREAD

**Issue by michaelzero00** [jvolker/miq-nz-booking-tools#54]
Most recent update:
Expected behaviour: 
let myDates = ['2021-11-30']

Once I have navigated to the "Selected your intended arrival date" puppeteer will click to the correct month (in this case November).

Actual behaviour:

Puppeteer just stays on July and doesn't navigate to November.

**Comment by dannz89** [comment]
Downloaded and installed the software following the latest release and have the same issue. Not possible to 'restart search' once a date / month has been added, Puppeteer just stays on July.

**Comment by alexDrinkwater** [comment]
@michaelzero00 We might need to update the readme but this is the expected behavior now as explained in #43.

@dannz89 Settings are automatically saved and used in the next refresh. The restart search is only to restart once a date had been found which you either missed or did not want. In the past the application would need to be restarted.
